### ISSUE TITLE
Why use gulp-remember when there is gulp-cached?

### ISSUE THREAD

**Issue by bcherny** [ahaurw01/gulp-remember#16]
This probably isn't the right place for this question, but why use gulp-remember? Here's my build:

```coffee
gulp.src SRC.coffee
    .pipe do sourcemaps.init
    .pipe cached 'coffee'
    .pipe (coffee COFFEE_OPTIONS).on 'error', (_.partialRight error, 'CoffeeScript')
    .pipe do sourcemaps.write
    .pipe ngAnnotate NGANNOTATE_OPTIONS
    .pipe concat 'bundle.js'
    .pipe gulp.dest DISTDIR
```

This produces the correct result as far as rebuilding the file that changed, and concating it with the rest of the files that haven't.

When I add in gulp-remember, the result seems to be the same, though each incremental rebuild takes 3x longer. What am I missing here?

**Comment by ahaurw01** [comment]
gulp-cached and gulp-remember do very different things. gulp-cached basically filters **out** files that it has already seen and haven't changed. gulp-remember adds files **in** that it has seen and are not present in the stream. They work very well together to exclude everything that hasn't changed, do processing on only those files that have changed, then add the other files back in so you can concat or bundle or do whatever business that requires all files of a certain type to be in the stream.

I can't speak to why your particular use case is confounding. Is it possible that ngAnnotate or sourcemaps are adding files back into the stream or reading from disk? I don't know anything about those plugins.

**Comment by bcherny** [comment]
Thanks for an explanation! That's a good place to start - I'll pare down my task an see how it behaves. Will report back in case anyone has this question in the future.

**Comment by ahaurw01** [comment]
Cool, sounds good. Don't hesitate to create another issue if you think gulp-remember isn't playing nice with somebody.

**Comment by htulipe** [comment]
@bcherny Did you found anything interesting about ngAnnotate and gulp-remember?
