### ISSUE TITLE
Letter case

### ISSUE THREAD

**Issue by TrySound** [ahaurw01/gulp-remember#21]
Paths `SomeThing` and `something` are equal. You should cache it in lower case and lowercase before check.

**Comment by ahaurw01** [comment]
Good find, thanks. Did you come across this by renaming files during your build process or something? I can patch this at some point, or feel free to beat me to it with a PR.

**Comment by TrySound** [comment]
@ahaurw01 Yeah. It's angular. I'm trying to find a good name for directive which evaluates like this
`ABComponent -> <a-b-component></a-b-component>`
`AbComponent -> <ab-component></ab-component>`
And I don't have access to external repos on my work. So would be good if you will find a time.

**Comment by TrySound** [comment]
I think path should be lowercased in this places.
https://github.com/ahaurw01/gulp-remember/blob/master/index.js#L27
https://github.com/ahaurw01/gulp-remember/blob/master/index.js#L64

**Comment by ahaurw01** [comment]
Just published a new version. Let me know if anything is amiss.

**Comment by TrySound** [comment]
@ahaurw01 Cool. Thanks!
