### ISSUE TITLE
Weird behavior - Forgets source Jade files replacing them with compiled HTML

### ISSUE THREAD

**Issue by name-k** [ahaurw01/gulp-remember#23]
The problem is - on the first run, gulp-remember remembers all the files and initial compilation goes fine, but starting from the second run, a part of previously remembered files are replaced with compiled HTML files. 

In the task below, all *.jade files are passed to the stream, but only root-to-base-folder files are being compiled. 
```
'use strict';

const 
  gulp     = require('gulp'),
  combiner = require('stream-combiner2').obj,
  $        = require('gulp-load-plugins')();

module.exports = function(options) {
  return function() {
    return combiner(
      gulp.src(options.src, {
        since : gulp.lastRun(options.taskName)
      }),
      $.if(options.flags.debug, $.debug({title : 'DEBUG ' + options.taskName + ':src'})),

      $.if(function(file) {
        return /\.jade$/.test(file.relative);
      }, 
        combiner(
        $.remember('templates'),
        $.if(options.flags.debug, $.debug({title : 'DEBUG ' + options.taskName + ':remembered'}))    
      )),

      $.if(function(file) {
        return /^[a-zA-Z0-9-_]+\.jade$/.test(file.relative);
      },
        combiner(
          $.jade(),
          $.if(options.flags.debug, $.debug({title : 'DEBUG ' + options.taskName + ':compiled'})),
          gulp.dest(options.dest),
          $.if(options.flags.debug, $.debug({title : 'DEBUG ' + options.taskName + ':dest'}))
        ) 
      ),

    ).on('error', $.notify.onError(function(err) {
      console.log(err);
        return {
          title : 'Templates',
          message: err.message
        };
    }));  
  };
};
```
On the second run (triggered by gulp.watch), no files will be passed to ```$.jade()``` because all root jade files are respectfully replaced (replaced in gulp-remember cache) with compiled html files and there are no more files to match ```/^[a-zA-Z0-9-_]+\.jade$/.test(file.relative)```. 

The question is how to avoid this behavior? 
I want to remember only jade files and I want them to be deleted or replaced from the stream only with ```forget``` method.

**Comment by name-k** [comment]
I should mention this is gulp v4
And the project setup is based on this one - https://github.com/name-k/frontend-template

**Comment by ahaurw01** [comment]
I haven't grokked what you're doing here in the task, but the issue you are seeing might be the one that came up previously with somebody else. Do these links help explain what you are seeing?

https://github.com/ahaurw01/gulp-remember#forgetting-files-with-altered-paths
https://github.com/ahaurw01/gulp-remember/issues/1
https://github.com/ahaurw01/gulp-remember/issues/18
